### ISSUE TITLE
Tracker is Down

### ISSUE THREAD

**Issue by Edward-Stryfe** [feross/webtorrent-www#112]
I've installed the webtorrent plugin for Vuze and the announces are telling me that the webtorrent.io tracker is not connecting. IT says, 

"Connection failed., UnresolvedAddressException"

Other webTorrent trackers like OpenWEBTorrrent tracker and my version of `bittorrent-tracker`  work perfectly fine. I'm not sure if the server you were running it on crashed from the load or you need to register the IP to the domain again but it's been ~24 hours and still no connection.

**Comment by demoneaux** [comment]
The tracker was closed in #106, as it was just supposed to serve as a tech demo. Now there are various tracker servers run by others in the community, with better resources to support them.

**Comment by Edward-Stryfe** [comment]
Well shouldn't it be removed from the list of default trackers then?

**Comment by demoneaux** [comment]
That would be great, but it's up to the people who maintain the Vuze plugin; we don't have control over that.

**Comment by Edward-Stryfe** [comment]
No the torrent was created using instant.io and the webtorrent-desktop

**Comment by demoneaux** [comment]
Well, the server was shutdown pretty recently, so it'll take time for things to update. AFAIK, it should be removed in the latest WebTorrent Desktop and instant.io.

**Comment by Edward-Stryfe** [comment]
Alright yeah. Thanks.
