### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-www#15]
https://github.com/sashahilton00/webtorrent-site

**Comment by feross** [comment]
https://www.uproxy.org/

**Comment by feross** [comment]
A basic site design, designed by @sashahilton00 is live at https://webtorrent.io now!

Next, let's work on getting an FAQ, docs, demos, and other cool stuff up!

Help needed! If you're looking a way to get involved with WebTorrent, please help with the website!

**Comment by sashahilton00** [comment]
Yeah, sorry I didn't manage to get any further, life got busy. i will try to add some more to it in the future, but for now the framework to easily add content is there :)
