### ISSUE TITLE
New page: Get started

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-www#19]
- Tutorial
- Basic code samples
- Friendly, helpful video

**Comment by Edward-Stryfe** [comment]
Could you work on relatively detailed tutorial on how to just use the stream function like you did on the homepage. I want to use webtorrent on my site but I am going to be using a cloud server with JS support. The only function I need though is to download and display and seed the video while only showing the video stream. I can't find a tutorial anywhere and I'm not an expert in JS so I cannot figure my way through the code of either webtorrent.min.js webtorrent-www or the webtorrent repository. Please help.

**Comment by SakyaStelios** [comment]
:+1:

**Comment by demoneaux** [comment]
I think this issue can be closed, as there's already a Getting Started page.

**Comment by feross** [comment]
Yep, sounds good to me!
