### ISSUE TITLE
Border on video shows up in fullscreen

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-www#25]

**Comment by sashahilton00** [comment]
@feross would you mind pushing the contents of the secret and torrents folders to the repo, as one cannot pull the newest files down from the server as it requires your ssh credentials. In the meantime, check out <link>https://developer.mozilla.org/en-US/docs/Web/CSS/%3Afullscreen</link> for a pseudo class that should handle the fullscreen css for the video element. Something like:

<code>
#videoWrap video:fullscreen {
border: none;
}
</code>

**Comment by feross** [comment]
@sashahilton00 

I can't push the contents of the "secret" folder -- it contains the TLS private key for HTTPS. However, I just made the secret folder optional. If the private key and certificate files are missing then only an HTTP server will be started. :+1: 

Working on a solution for the "torrents" folder right now.

**Comment by sashahilton00** [comment]
Ah right, should have seen that one coming ;) Regarding the other issue you were having with the tracker going down, why not just run 2 instances of node, and thus only shut off the website when updating as opposed to both site and tracker?

**Comment by feross** [comment]
@sashahilton00 Yep that would probably work.

**Comment by feross** [comment]
This is fixed now!
