### ISSUE TITLE
How to get this set up?

### ISSUE THREAD

**Issue by RaulTsc** [feross/webtorrent-www#39]
After doing ` npm install ` and ` npm build `  I can't do ` npm start ` . Am I missing something or is this a bug?

http://imgur.com/Vl5B5TS

**Comment by feross** [comment]
@RaulTsc Thanks for opening this issue. This was a bug that happens when you try to run the site locally without using TLS keys for HTTPS (since these are not checked into the github repository, obviously).

Just fixed it, so you can run the site locally now.
