### ISSUE TITLE
Disable automatic downloading for users on metered connections

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-www#40]
See: https://news.ycombinator.com/item?id=10923152

**Comment by sharpety12** [comment]
I'd like to help with this. I'll try to post a solution later today. I think it would also be a good idea to limit the number of connections by default too since that can usually cause serious lag on the whole network.

**Comment by feross** [comment]
@sharpety12 Thanks – looking forward to seeing your solution. Cheers!

**Comment by feross** [comment]
Fixed by https://github.com/feross/webtorrent-www/pull/69
