### ISSUE TITLE
Make site look decent on mobile

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-www#49]
Some simple responsive CSS would go a long way to making the site look decent on mobile.

**Comment by harperj** [comment]
I'm planning to work on this.

**Comment by harperj** [comment]
Made many changes to make this look better on mobile in #56.

I removed the top menu, since those links are elsewhere.  We could potentially re-add them, hidden behind a button.  Otherwise they should go, because they send the demo below the fold.

**Comment by feross** [comment]
Fixed by #56
