### ISSUE TITLE
Installation of WWW Demo for Begginers

### ISSUE THREAD

**Issue by rebitti** [feross/webtorrent-www#57]
Hello, im trying to install this website demo and im getting this error on Ubuntu 16.04

/home/feross/www/webtorrent.io/bin# ./deploy.sh
Already up-to-date.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
extract:xhr → gunzTarPerm ▌ ╢█████████████████████████████████████████░░░░░░░░░░░░░░░░░░╟
./deploy.sh: line 14: 15602 Killed                  npm install --production --quiet

Im really dont know how to start to install, im starting from this shell script 'deploy.sh'...

my pkg:
dpkg -s nodejs  Package: nodejs  Version: 5.11.1-1nodesource1~xenial1

thanks !

**Comment by rebitti** [comment]
Fixed this error, i didnt createa swap , memory problems...

now 

/node-icu-charset-detector.cpp:7:28: fatal error: unicode/ucsdet.h: No such file or directory

> webtorrent-www@0.0.1 build-js /home/feross/www/webtorrent.io-build
> browserify client > static/bundle.js

webtorrent: ERROR (no such process)
webtorrent: ERROR (no such process)

**Comment by rebitti** [comment]
Fixed  icu-charset problem  with

apt-get install libicu-dev

But still getting 
webtorrent: ERROR (no such process)
webtorrent: ERROR (no such process)

**Comment by feross** [comment]
This is not a demo of webtorrent on a website. This is the code for the actual site on https://webtorrent.io and it's much more complicated that what you need to get a basic demo working. 

You should look at the Complete HTML page example here: https://webtorrent.io/intro instead.
