### ISSUE TITLE
Raw html from faq page is not interpreted

### ISSUE THREAD

**Issue by yciabaud** [feross/webtorrent-www#70]
The code from the youtube videos and the slides are encoded to html entitties and therefore not interpreted by the browser.

**Comment by feross** [comment]
This used to work correctly. @dcposch changed the markdown renderer that we're using from `marked` to `remarkable`. This is probably related to that change.

Any ideas?

**Comment by feross** [comment]
Ah, we just need to pass the `{ html: true }` to indicate that we trust the markdown being passed in and want to render the HTML contained within. See https://github.com/jonschlinkert/remarkable#constructor

**Comment by feross** [comment]
PR here: https://github.com/feross/webtorrent-www/pull/71
